---
title: "Untitled"
author: "Corinne"
date: "4/14/2021"
output: html_document
---

```{r}
require(grid)
require(gridExtra)
require(ggpubr)

```

```{r}
baker <- c()
baker[1] <- rgb(56, 95, 150, maxColorValue = 255)
baker[2] <- rgb(207, 89, 33, maxColorValue = 255)
baker[3] <- rgb(158, 184, 219, maxColorValue = 255)
baker[4] <- rgb(231, 184, 0, maxColorValue = 255)
baker[5] <- rgb(128, 0, 0, maxColorValue = 255)

```

```{r}
load('C:/Users/cbowers/Desktop/dem.Rdata')
load('C:/Users/cbowers/Desktop/buildings.Rdata')
load('C:/Users/cbowers/Desktop/foundations.Rdata')
load('C:/Users/cbowers/Desktop/depthdamage.Rdata')
load('C:/Users/cbowers/Desktop/samples.Rdata')

load('C:/Users/cbowers/Desktop/catalog.Rdata')

```

## compute full loss histogram
```{r}
## look at losses for different storm years
# year <- 1995; year.id <- 89; loss.est <- 50*(91.6/155) * 1.68e6
# year <- 2006; year.id <- 249; loss.est <- 104*(91.6/155) * 1.28e6
# year <- 2017; year.id <- 421; loss.est <- 15.2*(91.6/155) * 1.04e6
year <- 2019; year.id <- 459; loss.est <- 91.6e6

# load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, '/mc_beta/prcp4/AR.Rdata'))
load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, '/mc_beta/prcp4/PRCP.Rdata'))
load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, '/mc_beta/prcp4/Q.Rdata'))
load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, '/mc_beta/prcp4/INUN.Rdata'))
# load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, '/mc_beta/prcp4/DM.Rdata'))
load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, '/mc_beta/prcp4/DV.Rdata'))

ggplot(loss.sim %>% filter(n.AR == 1)) + 
  geom_histogram(aes(x = loss, y = ..density..), color = 'black', fill = 'grey90', 
                 bins = sqrt(nrow(loss.sim)), boundary = 0) + 
  geom_vline(xintercept = loss.est, size = 1, linetype = 'dashed') + 
  scale_x_origin('Estimated Loss', 
    labels = comma_format(scale = 1e-6, prefix = '$', suffix = 'M', accuracy = 1)) + 
  scale_y_origin('Frequency of Occurrence') + 
  # coord_cartesian(xlim = c(0, 305e6)) +
  ggtitle(paste0(year, ' Event'))
ggsave(paste0('C:/Users/cbowers/Desktop/hist', year, '.jpg'), width = 5, height = 4)

nrow(loss.sim)/1e4
1 - (sum(loss.sim$loss > loss.est) / 1e4)

```

```{r}
## spatial distribution of loss
sonoma_cbgs <- block_groups(state = 'CA', county = 'Sonoma')
sonoma_blocks <- blocks(state = 'CA', county = 'Sonoma')
wbd12 <- st_read('D:/Research/_gis/California/_floodhazard/WBD_18_HU2_Shape/Shape/WBDHU12.shp',
                 quiet = TRUE) %>% st_transform(4269)

# buildings <- buildings %>%
#   st_as_sf(coords = c('X', 'Y'), crs = 4269) %>%
#   st_intersection(sonoma %>% transmute(tract = toNumber(GEOID))) %>%
#   st_intersection(sonoma_cbgs %>% transmute(blockgroup = toNumber(GEOID))) %>%
#   st_intersection(sonoma_blocks %>% transmute(block = toNumber(GEOID10))) %>% 
#   st_intersection(wbd12 %>% transmute(huc12 = HUC12)) 
# buildings <- buildings %>% 
#   st_drop_geometry %>% 
#   cbind(st_coordinates(buildings))
# save(buildings, file = 'C:/Users/cbowers/Desktop/buildings.Rdata')

## census tracts
load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, '/mc_beta/prcp4/DV_tract.Rdata'))
sonoma %>% 
  mutate(group = toNumber(GEOID)) %>% 
  left_join(loss.group, by = 'group') %>% 
  mutate(loss = ifelse(is.na(loss), 0, loss)) %>% 
  st_transform(6417) %>% st_crop(aoi) %>% 
  ggplot() + 
  geom_sf(data = sonoma %>% st_transform(6417), fill = 'grey90', color = 'grey60') +
  geom_sf(aes(fill = log10(loss+1)), color = NA) + 
  geom_sf(data = sonoma %>% st_transform(6417), fill = NA, color = 'grey60') +
  geom_sf(data = aoi, fill = NA, color = 'grey40') + 
  geom_sf(data = russian %>% st_crop(sonoma), size = 1) + 
  scale_fill_scico(palette = 'oslo', direction = -1)

## census block groups
load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, '/mc_beta/prcp4/DV_blockgroup.Rdata'))
sonoma_cbgs %>% 
  mutate(group = toNumber(GEOID)) %>% 
  left_join(loss.group, by = 'group') %>% 
  mutate(loss = ifelse(is.na(loss), 0, loss)) %>% 
  st_transform(6417) %>% st_crop(aoi) %>% 
  ggplot() + 
  geom_sf(data = sonoma %>% st_transform(6417), fill = 'grey90', color = 'grey60') +
  geom_sf(aes(fill = log10(loss+1)), color = NA) + 
  geom_sf(data = sonoma %>% st_transform(6417), fill = NA, color = 'grey60') +
  geom_sf(data = aoi, fill = NA, color = 'grey40') + 
  geom_sf(data = russian %>% st_crop(sonoma), size = 1) + 
  scale_fill_scico(palette = 'oslo', direction = -1)

## census blocks
load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, '/mc_beta/prcp4/DV_block.Rdata'))
sonoma_blocks %>% 
  mutate(group = toNumber(GEOID10)) %>% 
  left_join(loss.group, by = 'group') %>% 
  mutate(loss = ifelse(is.na(loss), 0, loss)) %>% 
  st_transform(6417) %>% st_crop(aoi) %>% 
  ggplot() + 
  geom_sf(data = sonoma %>% st_transform(6417), fill = 'grey90', color = 'grey60') +
  geom_sf(aes(fill = log10(loss+1)), color = NA) + 
  geom_sf(data = sonoma %>% st_transform(6417), fill = NA, color = 'grey60') +
  geom_sf(data = aoi, fill = NA, color = 'grey40') + 
  geom_sf(data = russian %>% st_crop(sonoma), size = 1) + 
  scale_fill_scico(palette = 'oslo', direction = -1)

## HUC-12 watersheds
load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, '/mc_beta/prcp4/DV_huc12.Rdata'))
wbd12 %>% 
  mutate(group = toNumber(HUC12)) %>% 
  left_join(loss.group %>% mutate(group = toNumber(group)), by = 'group') %>% 
  mutate(loss = ifelse(is.na(loss), 0, loss)) %>% 
  st_transform(6417) %>% st_crop(aoi) %>% 
  ggplot() + 
  geom_sf(data = sonoma %>% st_transform(6417), fill = 'grey90', color = 'grey60') +
  geom_sf(aes(fill = log10(loss+1)), color = NA) + 
  geom_sf(data = sonoma %>% st_transform(6417), fill = NA, color = 'grey60') +
  geom_sf(data = aoi, fill = NA, color = 'grey40') + 
  geom_sf(data = russian %>% st_crop(sonoma), size = 1) + 
  scale_fill_scico(palette = 'oslo', direction = -1)

```

```{r}
## calculate real vs. simulated PRCP & Q
loss.merged <- loss.sim %>% 
  full_join(precip %>% select(n.precip, IVT_max, duration, precip_mm),
            by = 'n.precip') %>%
  full_join(hydrograph %>% select(n.precip, n.runoff, n.hydro, runoff_mm, Qp_m3s, tp_hrs), 
            by = c('n.precip', 'n.runoff', 'n.hydro')) %>% 
  mutate(loss = ifelse(is.na(loss), 0, loss))

g1 <- loss.merged %>% 
  group_by(n.precip) %>% 
  summarize(
    precip_mm = precip_mm[1], loss.mean = mean(loss), 
    loss.lower = quantile(loss, 0.05), loss.upper = quantile(loss, 0.95)) %>% 
  ggplot() + 
  geom_segment(aes(x = precip_mm, xend = precip_mm, 
                   y = loss.lower, yend = loss.upper), color = 'grey70') + 
  geom_point(aes(x = precip_mm, y = loss.mean), alpha = 0.25) + 
  geom_hline(yintercept = loss.est, size = 1, linetype = 'dashed') + 
  geom_vline(xintercept = toNumber(catalog[year.id, 'precip']), color = 'red') + 
  scale_x_origin('Precipitation (in)', labels = comma_format(scale = 1/25.4, accuracy = 1), 
                 breaks = seq(0, 20*25.4, 25.4)) + 
  scale_y_origin('Expected Loss ($M)', labels = comma_format(scale = 1e-6)) + 
  # coord_cartesian(ylim = c(0,300e6)) +
  ggtitle(paste(year, 'Event'))
# ggsave('precip1995.jpg', width = 5, height = 4)

mft <- 3.28084
g2 <- loss.merged %>% 
  group_by(n.precip, n.runoff, n.hydro) %>% 
  summarize(
    Qp_m3s = Qp_m3s[1], loss.mean = mean(loss), 
    loss.lower = quantile(loss, 0.05), loss.upper = quantile(loss, 0.95),
    .groups = 'drop') %>% 
  ggplot() + 
  geom_segment(aes(x = Qp_m3s, xend = Qp_m3s, 
                   y = loss.lower, yend = loss.upper), color = 'grey70') + 
  geom_point(aes(x = Qp_m3s, y = loss.mean), alpha = 0.25) + 
  geom_hline(yintercept = loss.est, size = 1, linetype = 'dashed') + 
  geom_vline(xintercept = toNumber(catalog[year.id, 'Qp'])/mft^3, color = 'red') + 
  scale_x_origin('Streamflow (m3/s)', labels = comma) + 
  scale_y_origin('Expected Loss ($M)', labels = comma_format(scale = 1e-6)) + 
  # coord_cartesian(ylim = c(0,300e6)) +
  ggtitle(paste(year, 'Event'))
# ggsave('flow1995.jpg', width = 5, height = 4)

ggarrange(g1, g2, ncol = 2)
# ggsave(paste0(year, '.jpg'), width = 9, height = 5)

catalog[year.id,]

```

plot results from running PARRA for the entire catalog
```{r}
## load full simulation
load(paste0('D:/Research/_sherlock/1. PARRA/_results/full/AR.Rdata'))
load(paste0('D:/Research/_sherlock/1. PARRA/_results/full/PRCP.Rdata'))
load(paste0('D:/Research/_sherlock/1. PARRA/_results/full/Q.Rdata'))
load(paste0('D:/Research/_sherlock/1. PARRA/_results/full/INUN.Rdata'))
load(paste0('D:/Research/_sherlock/1. PARRA/_results/full/DM.Rdata'))
load(paste0('D:/Research/_sherlock/1. PARRA/_results/full/DV.Rdata'))

loss.merged <- loss.sim %>% 
  full_join(precip %>% 
              select(n.AR, n.precip, precip = precip_mm), 
            by = c('n.AR', 'n.precip')) %>% 
  full_join(hydrograph %>% 
              select(n.AR, n.precip, runoff = runoff_mm, Qp = Qp_m3s), 
            by = c('n.AR', 'n.precip')) %>% 
  mutate(runoff = ifelse(is.na(runoff), 0, runoff),
         Qp = ifelse(is.na(Qp), 0, Qp),
         loss = ifelse(is.na(loss), 0, loss))

g1 <- ggplot() + 
  geom_point(data = loss.merged, aes(x = precip, y = loss), color = 'grey70') + 
  geom_point(data = loss.merged %>% filter(n.AR == 89), 
             aes(x = precip, y = loss, color = '1995')) + 
  geom_point(data = loss.merged %>% filter(n.AR == 249), 
             aes(x = precip, y = loss, color = '2006')) + 
  geom_point(data = loss.merged %>% filter(n.AR == 459), 
             aes(x = precip, y = loss, color = '2019')) + 
  scale_color_manual('Year', values = baker[-3],
                     guide = guide_legend(override.aes = list(size = 2))) +
  scale_x_origin('Precipitation (in)', labels = comma_format(scale = 1/25.4, accuracy = 1), 
                 breaks = seq(0, 30*25.4, 5*25.4)) + 
  scale_y_origin('Expected Loss ($M)', labels = comma_format(scale = 1e-6)) + 
  coord_cartesian(xlim = c(0, 30*25.4), ylim = c(0, 750e6), clip = 'off')
g2 <- ggplot() + 
  geom_point(data = loss.merged, aes(x = Qp, y = loss), color = 'grey70') + 
  geom_point(data = loss.merged %>% filter(n.AR == 89), 
             aes(x = Qp, y = loss, color = '1995')) + 
  geom_point(data = loss.merged %>% filter(n.AR == 249), 
             aes(x = Qp, y = loss, color = '2006')) + 
  geom_point(data = loss.merged %>% filter(n.AR == 459), 
             aes(x = Qp, y = loss, color = '2019')) + 
  scale_color_manual('Year', values = baker[-3],
                     guide = guide_legend(override.aes = list(size = 2))) +
  scale_x_origin('Streamflow (m3/s)', labels = comma) + 
  scale_y_origin('Expected Loss ($M)', labels = comma_format(scale = 1e-6)) + 
  coord_cartesian(xlim = c(0, 2500), ylim = c(0, 750e6), clip = 'off')

# ggplot() + geom_point(data = loss.merged, aes(x = precip, y = Qp))

ggarrange(g1, g2, ncol = 2, common.legend = TRUE, legend = 'bottom')

```


## estimate return period for losses 
```{r}
temp <- read_csv('C:/Users/cbowers/Downloads/data.csv', skip = 22, n_max = 8) %>% 
  mutate(AEP = (str_locate(temp$Statistic, '-')[,'start'] - 1) %>% 
           str_sub(Statistic, end = .) %>% toNumber) %>% 
  mutate(RP = 1/(AEP/100)) %>% 
  mutate(flow_m3s = Value / mft^3)

lm(log(RP) ~ flow_m3s, data = temp) %>% summary
ggplot() + 
  geom_point(data = temp, aes(x = flow_m3s, y = RP)) + 
  geom_line(data = data.frame(dx = seq(100, 5000, 10)),
            aes(x = dx, y = exp(1.683e-03*dx-7.154e-01))) + 
  scale_x_origin() #+ scale_y_log10()
  
g1 <- loss.merged %>% 
  mutate(RP = exp(1.683e-03*Qp - 7.154e-01)) %>% 
  # arrange(desc(RP)) %>% View
  ggplot() + geom_point(aes(x = RP, y = loss)) + 
  scale_x_origin('Return Period (years)') + 
  scale_y_origin('Expected Loss ($M)', labels = comma_format(scale = 1e-6)) +
  theme(axis.title.y = element_blank(), axis.text.y = element_blank())
g2 <- loss.merged %>% 
  ggplot() + geom_point(aes(x = Qp/mft^3, y = loss)) +
  scale_x_origin('Streamflow @ USGS 11463500 (m3/s)') + 
  scale_y_origin('Expected Loss ($M)', labels = comma_format(scale = 1e-6))
cowplot::plot_grid(g2, g1, ncol = 2, align = 'hv')
ggsave('C:/Users/cbowers/Desktop/temp.jpg', width = 10, height = 5)

loss.merged %>% 
  mutate(RP = exp(1.683e-03*Qp - 7.154e-01)) %>% 
  summarize(annual_loss = Mean(loss/RP)/1e6)
  summarize(annual_loss = Sum(loss/RP)/1e6/100/33)
## based on this, the AAL is $118M

118/386
## does Sonoma represent ~30% of CA's flood losses?

claims %>% 
  mutate(sonoma = (toNumber(censustract) %in% toNumber(sonoma$GEOID))) %>% 
  group_by(sonoma) %>% 
  summarize(total_loss = Sum(amountpaidonbuildingclaim) + Sum(amountpaidoncontentsclaim)) %>% 
  mutate(pct_loss = total_loss/sum(total_loss))
## according to claims, it's only 18%

## what would the AAL be according to claims?
claims %>% 
  filter(toNumber(censustract) %in% toNumber(sonoma$GEOID)) %>% 
  summarize(total_loss = Sum(amountpaidonbuildingclaim) + Sum(amountpaidoncontentsclaim)) %>% 
  mutate(AAL = total_loss/diff(range(year(claims$dateofloss)))/1e6*30)
## about $53M, or ~14% of the CA total

loss.merged %>% 
  arrange(loss) %>% 
  mutate(RP = (1:nrow(.))*33/nrow(.)) %>%
  # mutate(RP2 = exp(1.683e-03*Qp - 7.154e-01)) %>% 
  # ggplot() + 
  # geom_point(aes(x = loss, y = RP1, color = 'RP1')) + 
  # geom_point(aes(x = loss, y = RP2, color = 'RP2')) + 
  # scale_x_origin(labels = comma_format(scale = 1e-6, prefix = '$', suffix = 'M')) + 
  # scale_y_origin()
  summarize(annual_loss = Sum(loss/RP)/1e6/100/33)

g1 <- ggplot() + 
  geom_point(data = temp, aes(x = flow_m3s, y = RP)) + 
  geom_line(data = data.frame(dx = seq(100, 5000, 10)),
            aes(x = dx, y = exp(1.683e-03*dx-7.154e-01))) + 
  scale_x_origin() + scale_y_origin('Return Period (years)') + 
  coord_cartesian(xlim = c(0,5000), clip = 'off') + 
  theme(axis.title.x = element_blank(), axis.text.x = element_blank())
g2 <- ggplot() + 
  geom_histogram(data = catalog, aes(x = Qp/mft^3), boundary = 0,
                 color = 'black', fill = 'grey90', bins = 20) +
  scale_x_origin('Streamflow @ USGS 11463500 (m3/s)') + scale_y_origin() + 
  coord_cartesian(xlim = c(0,5000), clip = 'off') +
  theme(axis.title.y = element_blank(), axis.text.y = element_blank(), 
        axis.ticks.y = element_blank())
cowplot::plot_grid(g1, g2, nrow = 2, align = 'v', rel_heights = c(2,1)) 

```

```{r}
## alternative return period method
ggplot() + 
  geom_point(data = loss.merged %>% arrange(desc(loss)) %>% 
               mutate(exceed = (1:nrow(.))/3200) %>% mutate(RP = 1/exceed),
             aes(x = RP, y = loss)) + 
  geom_point(data = loss.merged %>% group_by(n.AR) %>% 
               summarize(loss.mean = mean(loss)) %>% arrange(desc(loss.mean)) %>% 
               mutate(exceed = (1:nrow(.))/32) %>% 
               mutate(RP = 1/exceed),
             aes(x = RP, y = loss.mean), color = 'red') + 
  # scale_x_origin('Return Period (years)') + 
  scale_x_log10() +
  scale_y_origin('Loss ($M)', labels = comma_format(scale = 1e-6))
## it seems like the larger catalog is in fact hazard-consistent

loss.merged %>% 
  arrange(desc(loss)) %>% 
  mutate(exceed = (1:nrow(.))/3200) %>% 
  ggplot() + 
  geom_point(aes(x = loss, y = exceed)) + 
  scale_x_origin('Loss ($M)', labels = comma_format(scale = 1e-6)) + 
  scale_y_log10('Probability of Exceedance')

sum(loss.merged$loss/3200) / 1e6
## this is right in line with my other two estimates --> good! 

```

```{r}
## check the mitigated case
# load(paste0('D:/Research/_sherlock/1. PARRA/_results/full/AR.Rdata'))
# load(paste0('D:/Research/_sherlock/1. PARRA/_results/full/PRCP.Rdata'))
# load(paste0('D:/Research/_sherlock/1. PARRA/_results/full/Q.Rdata'))
load(paste0('D:/Research/_sherlock/1. PARRA/_results/full/INUN.Rdata'))

load('C:/Users/cbowers/Desktop/buildings.Rdata')
buildings <- buildings %>% 
  st_as_sf(coords = c('X', 'Y'), crs = 4269) %>% 
  st_transform(6417)

load(paste0('D:/Research/_sherlock/1. PARRA/_results/full/mitigated/DM.Rdata'))
load(paste0('D:/Research/_sherlock/1. PARRA/_results/full/mitigated/DV.Rdata'))

ggplot() + 
  geom_point(data = loss.merged %>% arrange(desc(loss)) %>%  mutate(exceed = (1:nrow(.))/3200),
             aes(x = loss, y = exceed)) +
  geom_point(data = loss.sim %>% arrange(desc(loss)) %>%  mutate(exceed = (1:nrow(.))/3200),
             aes(x = loss, y = exceed, color = 'mitigated')) + 
  scale_x_origin('Loss ($M)', labels = comma_format(scale = 1e-6)) + 
  scale_y_log10('Probability of Exceedance')

## why is the mitigated higher than the normal?

found_ht <- map_dfc(.x = 1:100, ~assign_foundations(buildings, nsi1.found))
temp <- data.frame(bldg = 1:nrow(buildings)) %>% 
  mutate(ht.05 = apply(found_ht, 1, function(x) quantile(x, 0.05)),
         ht.25 = apply(found_ht, 1, function(x) quantile(x, 0.25)),
         ht.median = apply(found_ht, 1, median),
         ht.mean = apply(found_ht, 1, mean),
         ht.75 = apply(found_ht, 1, function(x) quantile(x, 0.75)),
         ht.95 = apply(found_ht, 1, function(x) quantile(x, 0.95))) %>% 
  cbind(raised = buildings$raised_m)
ggplot(temp) + 
  geom_segment(aes(x = raised, xend = raised, y = ht.05, yend = ht.95), color = 'grey70') + 
  geom_point(aes(x = raised, y = ht.mean)) + 
  geom_parity()

```


## compare deterministic losses
```{r}
# model <- 'PRCP'
# load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year,
#             '/deterministic/', model, '_AR.Rdata'))
# load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year,
#             '/deterministic/', model, '_PRCP.Rdata'))
# load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year,
#             '/deterministic/', model, '_Q.Rdata'))
# load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year,
#             '/deterministic/', model, '_INUN.Rdata'))
# load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year,
#             '/deterministic/', model, '_DM.Rdata'))
# load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year,
#             '/deterministic/', model, '_DV.Rdata'))
# loss.prcp <- loss.sim
# loss.q <- loss.sim
# loss.inun <- loss.sim
# loss.dm <- loss.sim
# loss.dv <- loss.sim

load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, 
            '/deterministic/PRCP_DV.Rdata')); loss.prcp <- loss.sim
load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, 
            '/deterministic/Q_DV.Rdata')); loss.q <- loss.sim
load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, 
            '/deterministic/INUN_DV.Rdata')); loss.inun <- loss.sim
load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, 
            '/deterministic/DM_DV.Rdata')); loss.dm <- loss.sim
load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, 
            '/deterministic/DV_DV.Rdata')); loss.dv <- loss.sim

load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, 
            '/deterministic/zero/DV.Rdata'))
loss.det <- loss.sim$loss

apply(loss.prcp %>% select(-loss), 2, max)
apply(loss.q %>% select(-loss), 2, max)
apply(loss.inun %>% select(-loss), 2, max)
apply(loss.dm %>% select(-loss), 2, max)
apply(loss.dv %>% select(-loss), 2, max)


# ggplot() +
#   geom_density(aes(x = loss.prcp$loss, color = 'PRCP', fill = 'PRCP', y = ..scaled..),
#                size = 1, alpha = 0.25) +
#   geom_density(aes(x = loss.q$loss, color = 'Q', fill = 'Q', y = ..scaled..),
#                size = 1, alpha = 0.25) +
#   geom_density(aes(x = loss.inun$loss, color = 'INUN', fill = 'INUN', y = ..scaled..),
#                size = 1, alpha = 0.25) +
#   geom_density(aes(x = loss.dm$loss, color = 'DM', fill = 'DM', y = ..scaled..),
#                size = 1, alpha = 0.25) +
#   geom_density(aes(x = loss.dv$loss, color = 'DV', fill = 'DV', y = ..scaled..),
#                size = 1, alpha = 0.25) +
#   labs(color = 'Model', fill = 'Model') +
#   scale_x_origin(labels = comma_format(scale = 1e-6, prefix = '$', suffix = 'M')) +
#   scale_y_origin()

```

```{r}
xmax <- 90e6

g1 <- ggplot(loss.prcp) + 
  geom_density(aes(x = loss, y = ..scaled..), fill = 'grey90') +
  geom_text(data = data.frame(lab = 'G(PRCP)'), 
            aes(x = 60e6, y = 0.8, label = lab), fontface = 'bold') + 
  geom_vline(xintercept = loss.det, color = 'grey50') + 
  geom_vline(xintercept = loss.est, size = 1, linetype = 'dashed') + 
  scale_x_origin(labels = comma_format(scale = 1e-6, prefix = '$', suffix = 'M')) + 
  scale_y_origin() + 
  coord_cartesian(xlim = c(0, xmax)) + 
  theme(axis.title = element_blank(), 
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        plot.margin = margin(1,1,1,10))
g2 <- ggplot(loss.q) + 
  geom_density(aes(x = loss, y = ..scaled..), fill = 'grey90') +
  geom_text(data = data.frame(lab = 'G(Q)'), 
            aes(x = 60e6, y = 0.8, label = lab), fontface = 'bold') + 
  geom_vline(xintercept = loss.det, color = 'grey50') + 
  geom_vline(xintercept = loss.est, size = 1, linetype = 'dashed') + 
  scale_x_origin(labels = comma_format(scale = 1e-6, prefix = '$', suffix = 'M')) + 
  scale_y_origin() + 
  coord_cartesian(xlim = c(0, xmax)) + 
  theme(axis.title = element_blank(), 
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        plot.margin = margin(1,1,1,10))
g3 <- ggplot(loss.inun) + 
  geom_density(aes(x = loss, y = ..scaled..), fill = 'grey90') +
  geom_text(data = data.frame(lab = 'G(INUN)'), 
            aes(x = 60e6, y = 0.8, label = lab), fontface = 'bold') + 
  geom_vline(xintercept = loss.det, color = 'grey50') + 
  geom_vline(xintercept = loss.est, size = 1, linetype = 'dashed') + 
  scale_x_origin(labels = comma_format(scale = 1e-6, prefix = '$', suffix = 'M')) + 
  scale_y_origin() + 
  coord_cartesian(xlim = c(0, xmax)) + 
  theme(axis.title = element_blank(), 
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        plot.margin = margin(1,1,1,10))
g4 <- ggplot(loss.dm) + 
  geom_density(aes(x = loss, y = ..scaled..), fill = 'grey90') +
  geom_text(data = data.frame(lab = 'G(DM)'), 
            aes(x = 60e6, y = 0.8, label = lab), fontface = 'bold') + 
  geom_vline(xintercept = loss.det, color = 'grey50') + 
  geom_vline(xintercept = loss.est, size = 1, linetype = 'dashed') + 
  scale_x_origin(labels = comma_format(scale = 1e-6, prefix = '$', suffix = 'M')) + 
  scale_y_origin() + 
  coord_cartesian(xlim = c(0, xmax)) + 
  theme(axis.title = element_blank(), 
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        plot.margin = margin(1,1,1,10))
g5 <- ggplot(loss.dv) + 
  geom_density(aes(x = loss, y = ..scaled..), fill = 'grey90') +
  geom_text(data = data.frame(lab = 'G(DV)'), 
            aes(x = 60e6, y = 0.8, label = lab), fontface = 'bold') + 
  geom_vline(xintercept = loss.det, color = 'grey50') + 
  geom_vline(xintercept = loss.est, size = 1, linetype = 'dashed') + 
  scale_x_origin(labels = comma_format(scale = 1e-6, prefix = '$', suffix = 'M')) + 
  scale_y_origin() + 
  coord_cartesian(xlim = c(0, xmax)) + 
  theme(axis.title = element_blank(), 
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        plot.margin = margin(1,1,1,10))

ggarrange(g1, g4, g2, g5, g3, ncol = 2, nrow = 3) %>% 
  grid.arrange(top = textGrob(paste('Single-Model Uncertainty:', year, 'Event'), 
                              gp = gpar(size = 24)))

```

```{r}
## look at it from the other direction

load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, 
            '/reverse/PRCP_DV.Rdata')); loss.prcp <- loss.sim
load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, 
            '/reverse/Q_DV.Rdata')); loss.q <- loss.sim
load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, 
            '/reverse/INUN_DV.Rdata')); loss.inun <- loss.sim
load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, 
            '/reverse/DM_DV.Rdata')); loss.dm <- loss.sim
load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, 
            '/reverse/DV_DV.Rdata')); loss.dv <- loss.sim

load(paste0('D:/Research/_sherlock/1. PARRA/_results/event_', year, 
            '/reverse/all/DV.Rdata')); loss.all <- loss.sim

# ggplot() +
#   geom_density(aes(x = loss.prcp$loss, color = 'PRCP', fill = 'PRCP', y = ..scaled..),
#                size = 1, alpha = 0.25) +
#   geom_density(aes(x = loss.q$loss, color = 'Q', fill = 'Q', y = ..scaled..),
#                size = 1, alpha = 0.25) +
#   geom_density(aes(x = loss.inun$loss, color = 'INUN', fill = 'INUN', y = ..scaled..),
#                size = 1, alpha = 0.25) +
#   geom_density(aes(x = loss.dm$loss, color = 'DM', fill = 'DM', y = ..scaled..),
#                size = 1, alpha = 0.25) +
#   geom_density(aes(x = loss.dv$loss, color = 'DV', fill = 'DV', y = ..scaled..),
#                size = 1, alpha = 0.25) +
#   geom_vline(xintercept = loss.all, color = 'grey50') + 
#   labs(color = 'Model', fill = 'Model') +
#   scale_x_origin(labels = comma_format(scale = 1e-6, prefix = '$', suffix = 'M')) +
#   scale_y_origin()


xmax <- 100e6
xlabel <- 70e6
g1 <- ggplot(loss.prcp) + 
  geom_density(aes(x = loss, y = ..scaled..), fill = 'grey70') +
  geom_density(data = loss.all, aes(x = loss, y = ..scaled..), 
               color = 'grey50', fill = 'grey90', alpha = 0.25) + 
  geom_text(data = data.frame(lab = 'G(PRCP)'), 
            aes(x = xlabel, y = 0.8, label = lab), fontface = 'bold') + 
  geom_vline(xintercept = loss.est, size = 1, linetype = 'dashed') + 
  scale_x_origin(labels = comma_format(scale = 1e-6, prefix = '$', suffix = 'M')) + 
  scale_y_origin() + 
  coord_cartesian(xlim = c(0, xmax)) + 
  theme(axis.title = element_blank(), 
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        plot.margin = margin(1,1,1,10))
g2 <- ggplot(loss.q) + 
  geom_density(aes(x = loss, y = ..scaled..), fill = 'grey70') +
  geom_density(data = loss.all, aes(x = loss, y = ..scaled..), 
               color = 'grey50', fill = 'grey90', alpha = 0.25) + 
  geom_text(data = data.frame(lab = 'G(Q)'), 
            aes(x = xlabel, y = 0.8, label = lab), fontface = 'bold') + 
  geom_vline(xintercept = loss.est, size = 1, linetype = 'dashed') + 
  scale_x_origin(labels = comma_format(scale = 1e-6, prefix = '$', suffix = 'M')) + 
  scale_y_origin() + 
  coord_cartesian(xlim = c(0, xmax)) + 
  theme(axis.title = element_blank(), 
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        plot.margin = margin(1,1,1,10))
g3 <- ggplot(loss.inun) + 
  geom_density(aes(x = loss, y = ..scaled..), fill = 'grey70') +
  geom_density(data = loss.all, aes(x = loss, y = ..scaled..), 
               color = 'grey50', fill = 'grey90', alpha = 0.25) + 
  geom_text(data = data.frame(lab = 'G(INUN)'), 
            aes(x = xlabel, y = 0.8, label = lab), fontface = 'bold') + 
  geom_vline(xintercept = loss.est, size = 1, linetype = 'dashed') + 
  scale_x_origin(labels = comma_format(scale = 1e-6, prefix = '$', suffix = 'M')) + 
  scale_y_origin() + 
  coord_cartesian(xlim = c(0, xmax)) + 
  theme(axis.title = element_blank(), 
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        plot.margin = margin(1,1,1,10))
g4 <- ggplot(loss.dm) + 
  geom_density(aes(x = loss, y = ..scaled..), fill = 'grey70') +
  geom_density(data = loss.all, aes(x = loss, y = ..scaled..), 
               color = 'grey50', fill = 'grey90', alpha = 0.25) + 
  geom_text(data = data.frame(lab = 'G(DM)'), 
            aes(x = xlabel, y = 0.8, label = lab), fontface = 'bold') + 
  geom_vline(xintercept = loss.est, size = 1, linetype = 'dashed') + 
  scale_x_origin(labels = comma_format(scale = 1e-6, prefix = '$', suffix = 'M')) + 
  scale_y_origin() + 
  coord_cartesian(xlim = c(0, xmax)) + 
  theme(axis.title = element_blank(), 
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        plot.margin = margin(1,1,1,10))
g5 <- ggplot(loss.dv) + 
  geom_density(aes(x = loss, y = ..scaled..), fill = 'grey70') +
  geom_density(data = loss.all, aes(x = loss, y = ..scaled..), 
               color = 'grey50', fill = 'grey90', alpha = 0.25) + 
  geom_text(data = data.frame(lab = 'G(DV)'), 
            aes(x = xlabel, y = 0.8, label = lab), fontface = 'bold') + 
  geom_vline(xintercept = loss.est, size = 1, linetype = 'dashed') + 
  scale_x_origin(labels = comma_format(scale = 1e-6, prefix = '$', suffix = 'M')) + 
  scale_y_origin() + 
  coord_cartesian(xlim = c(0, xmax)) + 
  theme(axis.title = element_blank(), 
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        plot.margin = margin(1,1,1,10))

ggarrange(g1, g4, g2, g5, g3, ncol = 2, nrow = 3) %>% 
  grid.arrange(top = textGrob(paste('Single-Model Elimination:', year, 'Event'), 
                              gp = gpar(size = 24)))


```




