---
title: "Untitled"
author: "Corinne"
date: "11/9/2020"
output: html_document
---

```{r setup, include = FALSE}
# rm(list=ls())
root <- 'D:/Research'

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = root)

```

```{r packages}
require(caret)
require(randomForest)
require(earth)
require(gbm)
require(grid)
require(gridExtra)
require(factoextra)
require(ggforce)
require(mvtnorm)
require(ggrepel)
require(tidyverse); theme_set(theme_bw())

```

```{r functions}
## helper functions ####
toNumber <- function(x) as.numeric(paste(x))
sum.na <- function(x) sum(is.na(x))         
Mean <- function(x) ifelse(sum(is.na(x)) == length(x), NA, mean(x, na.rm = TRUE))
Sum <- function(x) sum(x, na.rm = TRUE)
Max <- function(x) max(x, na.rm = TRUE) 
Min <- function(x) min(x, na.rm = TRUE)

mft <- 3.28084

ggcolor <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}

```

```{r load data}
load('C:/Users/cbowers/Downloads/f.net.Rdata')
load('C:/Users/cbowers/Downloads/f.mars.Rdata')
load('C:/Users/cbowers/Downloads/f.rf.Rdata')
load('C:/Users/cbowers/Downloads/f.boost.Rdata')

load('C:/Users/cbowers/Downloads/regression_data.Rdata')

```

```{r}
## plot class balance donut charts ####
summary(df$y)
nrow(df)
ggplot() + 
  geom_rect(aes(xmin = 3, xmax = 4, ymin = 0, ymax = 19496, fill = 'No')) +
  geom_rect(aes(xmin = 3, xmax = 4, ymin = 19496, ymax = 21164, fill = 'Yes')) +
  coord_polar("y", start = 1) + 
  scale_fill_manual(values = c('lightskyblue1', 'dodgerblue4')) + 
  xlim(c(2,4)) + 
  theme_void()

summary(df.smote$y)
nrow(df.smote)
ggplot() + 
  geom_rect(aes(xmin = 3, xmax = 4, ymin = 0, ymax = 32304, fill = 'No')) +
  geom_rect(aes(xmin = 3, xmax = 4, ymin = 32304, ymax = 49802, fill = 'Yes')) +
  coord_polar("y", start = 0, direction = -1) + 
  scale_fill_manual(values = c('lightskyblue1', 'dodgerblue4')) + 
  xlim(c(2,4)) + 
  theme_void()

```

```{r}
## calculate ROC curve ####

index <- seq(0, 1, 0.01)
ROC_sens <- data.frame(matrix(nrow = length(index), ncol = 0))
ROC_spec <- data.frame(matrix(nrow = length(index), ncol = 0))
y.true <- factor(as.numeric(df.test$y)-1)

predictions.prob <- data.frame(
  net = predict(f.net, df.test, type = 'prob')$Yes, 
  mars = predict(f.mars, df.test, type = 'prob')$Yes, 
  rf = predict(f.rf, df.test, type = 'prob')$Yes, 
  boost = predict(f.boost, df.test, type = 'prob')$Yes)
for (id in 1:length(index)) {
  i <- index[id]
  
  matrix.net <- confusionMatrix(factor(ifelse(predictions.prob$net > i, 1, 0)), y.true)
  ROC_sens$net[id] <- matrix.net$byClass['Sensitivity']
  ROC_spec$net[id] <- 1 - matrix.net$byClass['Specificity']
 
  matrix.mars <- confusionMatrix(factor(ifelse(predictions.prob$mars > i, 1, 0)), y.true)
  ROC_sens$mars[id] <- matrix.mars$byClass['Sensitivity']
  ROC_spec$mars[id] <- 1 - matrix.mars$byClass['Specificity']
  
  matrix.rf <- confusionMatrix(factor(ifelse(predictions.prob$rf > i, 1, 0)), y.true)
  ROC_sens$rf[id] <- matrix.rf$byClass['Sensitivity']
  ROC_spec$rf[id] <- 1 - matrix.rf$byClass['Specificity']
  
  matrix.boost <- confusionMatrix(factor(ifelse(predictions.prob$boost > i, 1, 0)), y.true)
  ROC_sens$boost[id] <- matrix.boost$byClass['Sensitivity']
  ROC_spec$boost[id] <- 1 - matrix.boost$byClass['Specificity']
}

ggplot() + 
  geom_step(aes(x = ROC_spec$net, y = ROC_sens$net, color = 'net'), size = 1) +
  geom_step(aes(x = ROC_spec$mars, y = ROC_sens$mars, color = 'mars'), size = 0.5) +
  geom_step(aes(x = ROC_spec$rf, y = ROC_sens$rf, color = 'rf'), size = 0.5) +
  geom_step(aes(x = ROC_spec$boost, y = ROC_sens$boost, color = 'boost'), size = 1) +
  geom_abline(slope = 1, intercept = 0, linetype = 'dashed') + 
  ggtitle('ROC Curve') + 
  labs(x = '1 - Specificity (FN)', y = 'Sensitivity (FP)', color = 'Model') + 
  scale_x_continuous(expand = c(0.001,0.001)) + scale_y_continuous(expand = c(0.001,0.001)) + 
  scale_color_brewer(palette = 'Paired') + 
  # scale_color_manual(values = RColorBrewer::brewer.pal(4, 'Paired')[c(1,2,7,8)]) + 
  coord_fixed(ratio = 1) + 
  theme(panel.border = element_blank(), 
        axis.line = element_line(color = 'black'),
        panel.grid.major.x = element_line(color = 'gray95'))
  
## calculate prediction accuracy
predictions.class <- data.frame(
  net = predict(f.net, df.test), 
  mars = predict(f.mars, df.test), 
  rf = predict(f.rf, df.test), 
  boost = predict(f.boost, df.test))

TP <- apply(predictions.class, 2, function(x) x == df.test$y & df.test$y == 'Yes') %>% apply(2, sum)
FN <- apply(predictions.class, 2, function(x) x != df.test$y & df.test$y == 'Yes') %>% apply(2, sum)
FP <- apply(predictions.class, 2, function(x) x != df.test$y & df.test$y == 'No') %>% apply(2, sum)
TP / (TP + FP + FN)
## of the times that damages occur, this is the percentage that we're getting right

## calculate AUC
# pROC::auc

```

```{r}
## confusion matrix for f.rf
confusionMatrix(predict(f.rf, df.test), df.test$y)

## f-statistic: random forest case
cm <- confusionMatrix(predict(f.rf, df.test), df.test$y)$table
cm[2,2] / (cm[1,2] + cm[2,1] + cm[2,2])

## f-statistic: guessing case (numerical solution)
p <- 1 - sum(df.test$y == 'No')/nrow(df.test)
p^2 / (2*p*(1-p) + p^2)

```


#### PRINCIPAL COMPONENT ANALYSIS ####

```{r}
## get baseline PCA results
pca.results <- princomp(df.smote %>% dplyr::select(-y), cor = TRUE)
pca.var <- get_pca_var(pca.results)
pca.var

pca.eig <- get_eigenvalue(pca.results)
fviz_eig(pca.results)

## get k-nearest neighbor clustering results
knn <- kmeans(pca.var$coord, centers = 5, nstart = 10, iter.max = 1e3)
clusters <- pca.var$coord[,1:5] %>% 
  cbind(cluster = knn$cluster) %>% 
  as.data.frame %>% 
  cbind(varnames = row.names(.), .) 

## create raster contribution maps
temp <- pca.var$contrib %>% 
  as.data.frame %>% 
  cbind(varnames = row.names(.), .) %>% 
  pivot_longer(cols = -varnames, names_to = 'dim', values_to = 'contrib') %>% 
  full_join(data.frame(dim = row.names(pca.eig), weight = pca.eig$variance.percent)) %>% 
  mutate(dim = toNumber(gsub('Dim.', '', dim)),
         varnames = factor(varnames, levels = arrange(clusters, cluster)$varnames)) %>% 
  filter(dim <= 8)
ggplot(temp) +  
  geom_tile(aes(y = varnames, x = dim, fill = contrib*weight)) + 
  scale_x_continuous(breaks = 1:8) + 
  scale_fill_viridis_c(name = 'Weighted \nContribution')
ggplot(temp) +  
  geom_tile(aes(y = varnames, x = dim, fill = contrib>10), color = 'grey50') + 
  scale_fill_manual(name = 'Contribution \n < 10%', values = c('grey25', 'orange')) +
  scale_x_continuous(breaks = 1:8)

## create component vector diagrams
fviz_pca_var(pca.results, repel = TRUE)

g.pca <- ggplot(clusters) + 
  geom_circle(aes(x0 = 0, y0 = 0, r = 0.5), color = 'grey70') + 
  geom_circle(aes(x0 = 0, y0 = 0, r = 0.25), color = 'grey90') + 
  geom_circle(aes(x0 = 0, y0 = 0, r = 0.75), color = 'grey90') + 
  geom_hline(yintercept = 0, color = 'grey70') + 
  geom_vline(xintercept = 0, color = 'grey70') + 
  geom_circle(aes(x0 = 0, y0 = 0, r = 1)) + 
  theme(panel.border = element_blank(), panel.grid = element_blank(),
        axis.text = element_blank(), axis.ticks = element_line(color = 'white'),
        axis.title = element_text(face = 'bold', size = 14)) + 
  scale_x_continuous(expand = c(0,0)) + scale_y_continuous(expand = c(0,0)) + 
  coord_fixed(ratio = 1)
g.pca + 
  geom_segment(aes(x = 0, xend = Dim.1, y = 0, yend = Dim.2, color = factor(cluster))) +
  geom_point(aes(x = Dim.1, y = Dim.2, color = factor(cluster))) +
  labs(x = 'Dim1', y = 'Dim2', color = 'Cluster')
g.pca + 
  geom_segment(aes(x = 0, xend = Dim.1, y = 0, yend = Dim.3, color = factor(cluster))) +
  geom_point(aes(x = Dim.1, y = Dim.3, color = factor(cluster))) +
  labs(x = 'Dim1', y = 'Dim3', color = 'Cluster')

```

```{r}
## visualize PCA clusters on component vector diagrams
clusters <- clusters %>% 
  mutate(
    ifelse(varnames %in% c('SFH', 'population', 'impervious', 'developed'), 1, 
    ifelse(varnames %in% c('days.max', 'precip.max', 'precip.total', 'duration', 'IVT_max'), 2, 
    ifelse(varnames %in% c('precip.season', 'precip.prevmonth', 'rainyseason', 'rainyseason.month'), 3, 
    0)))
  )
clusters$printname <- paste(clusters$varnames)
clusters['SFH', 'printname'] <- 'homes.1unit'
clusters['days.max', 'printname'] <- 'days.of.rain'
clusters['duration', 'printname'] <- 'storm.duration'
clusters['IVT_max', 'printname'] <- 'storm.intensity'

g.pca <- ggplot(clusters) + 
  geom_circle(aes(x0 = 0, y0 = 0, r = 0.5), color = 'grey70') + 
  geom_circle(aes(x0 = 0, y0 = 0, r = 0.25), color = 'grey90') + 
  geom_circle(aes(x0 = 0, y0 = 0, r = 0.75), color = 'grey90') + 
  geom_hline(yintercept = 0, color = 'grey70') + 
  geom_vline(xintercept = 0, color = 'grey70') + 
  geom_circle(aes(x0 = 0, y0 = 0, r = 1)) + 
  theme(panel.border = element_blank(), panel.grid = element_blank(),
        axis.text = element_blank(), axis.ticks = element_line(color = 'white'),
        axis.title = element_text(face = 'bold', size = 14)) + 
  scale_x_continuous(expand = c(0,0)) + scale_y_continuous(expand = c(0,0)) + 
  coord_fixed(ratio = 1)

## plot without clusters
g.pca +
  geom_segment(aes(x = 0, xend = Dim.1, y = 0, yend = Dim.2), color = 'grey10') + 
  geom_point(aes(x = Dim.1, y = Dim.2), color = 'grey10') +
  ggtitle('Blank') + theme(plot.title = element_text(face = 'bold', size = 18)) + 
  labs(x = 'Dim1', y = 'Dim2', color = 'Cluster')
ggsave('D:/Research/_plots/pca0.jpg', width = 4, height = 4)

## plot with cluster #1
g.pca + 
  geom_segment(aes(x = 0, xend = Dim.1, y = 0, yend = Dim.2, 
               color = (group==1), size = (group==1)), show.legend = FALSE) +
  geom_point(aes(x = Dim.1, y = Dim.2, color = group==1), show.legend = FALSE) +
  scale_color_manual(values = c('grey10', 'tomato3')) + 
  scale_size_manual(values = c(0.5, 1.25)) +
  geom_label_repel(data = clusters %>% filter(group == 1), 
                   aes(x = Dim.1, y = Dim.2, label = printname),
                   segment.color = 'grey30', force = 1.5,
                   label.padding = 0.1, label.size = NA, label.r = .5) + 
  geom_segment(aes(x = 0, xend = Dim.1, y = 0, yend = Dim.2, 
               color = (group==1), size = (group==1)), 
               alpha = 0.1, show.legend = FALSE) +
  ggtitle('Cluster #1') + labs(x = 'Dim1', y = 'Dim2') +
  theme(plot.title = element_text(color = 'tomato3', face = 'bold', size = 18))
  
ggsave('D:/Research/_plots/pca1.jpg', width = 4, height = 4)

## plot with cluster #2
g.pca + 
  geom_segment(aes(x = 0, xend = Dim.1, y = 0, yend = Dim.2, 
               color = (group==2), size = (group==2)), show.legend = FALSE) +
  geom_point(aes(x = Dim.1, y = Dim.2, color = group==2), show.legend = FALSE) +
  scale_color_manual(values = c('grey10', ggcolor(3)[2])) + 
  scale_size_manual(values = c(0.5, 1.25)) +
  geom_label_repel(data = clusters %>% filter(group == 2), 
                   aes(x = Dim.1, y = Dim.2, label = printname),
                   segment.color = 'grey30', force = 2,
                   label.padding = 0.1, label.size = NA, label.r = .5) + 
  geom_segment(aes(x = 0, xend = Dim.1, y = 0, yend = Dim.2, 
               color = (group==2), size = (group==2)), 
               alpha = 0.1, show.legend = FALSE) +
  ggtitle('Cluster #2') + labs(x = 'Dim1', y = 'Dim2') +
  theme(plot.title = element_text(color = ggcolor(3)[2], face = 'bold', size = 18))
ggsave('D:/Research/_plots/pca2.jpg', width = 4, height = 4)

# ## plot with both clusters
# g.pca + 
#   geom_segment(aes(x = 0, xend = Dim.1, y = 0, yend = Dim.2, 
#                color = factor(group), size = factor(group)), show.legend = FALSE) +
#   geom_point(aes(x = Dim.1, y = Dim.2, color = factor(group)), show.legend = FALSE) +
#   scale_color_manual(values = c('grey10', 'tomato3', ggcolor(3)[2], 'grey10')) + 
#   scale_size_manual(values = c(0.5, 1.25, 1.25, 0.5)) +
#   geom_label_repel(data = clusters %>% filter(group %in% 1:2), 
#                    aes(x = Dim.1, y = Dim.2, label = printname),
#                    segment.color = 'grey30', force = 2,
#                    label.padding = 0.1, label.size = NA, label.r = .5) + 
#   geom_segment(aes(x = 0, xend = Dim.1, y = 0, yend = Dim.2, 
#                color = factor(group), size = factor(group)), 
#                alpha = 0.1, show.legend = FALSE) +
#   ggtitle('Clusters') + labs(x = 'Dim1', y = 'Dim2') +
#   theme(plot.title = element_text(face = 'bold', size = 18))
#  ggsave('D:/Research/_plots/pcaboth.jpg', width = 4, height = 4)
 
```

```{r}
#### visualize PCA 101 ####

## generate correlated data
set.seed(1)
data <- data.frame(mvtnorm::rmvnorm(100, mean = rep(5, 2), sigma = matrix(c(0.5, 0.6, 0.6, 1.25), nrow = 2)))
means <- apply(data, 2, mean)
X <- as.matrix(data) %>% apply(2, function(x) x-mean(x))
scores <- X %*% eigen(cov(X))$vectors

## get coordinates of PCA lines in original space
pc1 <- (matrix(c(-3.5,0, 3.5,0), ncol = 2, byrow = TRUE) %*% t(eigen(cov(X))$vectors)) %>% 
  sweep(2, means, '+') %>% data.frame
pc2 <- (matrix(c(0,-1.8, 0,1.8), ncol = 2, byrow = TRUE) %*% t(eigen(cov(X))$vectors)) %>% 
  sweep(2, means, '+') %>% data.frame

## plot original space
ggplot(data) + 
  geom_point(aes(x = X1, y = X2)) + 
  scale_x_continuous(limits = c(2,7.99), expand = c(0,0)) + 
  scale_y_continuous(limits = c(1,8.99), expand = c(0,0), breaks = 1:9) + 
  coord_fixed(ratio = 0.85) + 
  theme(panel.border = element_blank(),
        axis.line = element_line(size = 1, color = 'black'),
        axis.title = element_blank(), axis.text = element_blank(), axis.ticks = element_blank(),
        panel.grid.major = element_line(color = 'grey85'), panel.grid.minor = element_blank())
ggsave('D:/Research/_plots/pca101a.jpg', width = 4, height = 4)
ggplot(data) + 
  geom_segment(x = pc1[1,1], xend = pc1[2,1], y = pc1[1,2], yend = pc1[2,2],
               color = 'darkorange1', size = 1.5,
               arrow = arrow(ends = 'both', length = unit(0.1, "inches"))) +
  geom_segment(x = pc2[1,1], xend = pc2[2,1], y = pc2[1,2], yend = pc2[2,2],
               color = 'royalblue1', size = 1.5,
               arrow = arrow(ends = 'both', length = unit(0.1, "inches"))) +
  geom_point(aes(x = X1, y = X2)) + 
  scale_x_continuous(limits = c(2,7.99), expand = c(0,0)) + 
  scale_y_continuous(limits = c(1,8.99), expand = c(0,0), breaks = 1:9) + 
  coord_fixed(ratio = 0.85) + 
  theme(panel.border = element_blank(),
        axis.line = element_line(size = 1, color = 'black'),
        axis.title = element_blank(), axis.text = element_blank(), axis.ticks = element_blank(),
        panel.grid.major = element_line(color = 'grey85'), panel.grid.minor = element_blank())
ggsave('D:/Research/_plots/pca101b.jpg', width = 4, height = 4)

## plot transformed space
vert_grid <- expand.grid(x1 = 2:8, x2 = c(1,9)) %>% 
  arrange(x1) %>% as.matrix %>% sweep(2, means, '-')
vert_pca <- vert_grid %*% eigen(cov(X))$vectors
horiz_grid <- expand.grid(x1 = c(2,8), x2 = 1:9) %>% 
  arrange(x2) %>% as.matrix %>% sweep(2, means, '-')
horiz_pca <- horiz_grid  %*% eigen(cov(X))$vectors
intersection <- expand.grid(x1 = 5, x2 = 5) %>% 
  arrange(x1) %>% as.matrix %>% sweep(2, means, '-')
intersection <- intersection %*% eigen(cov(X))$vectors
ggplot() + 
  geom_segment(aes(x = vert_pca[seq(1,12,2),1], xend = vert_pca[seq(2,12,2),1],
                   y = vert_pca[seq(1,12,2),2], yend = vert_pca[seq(2,12,2),2]),
               color = 'grey85') +
  geom_segment(aes(x = horiz_pca[seq(1,16,2),1], xend = horiz_pca[seq(2,16,2),1],
                   y = horiz_pca[seq(1,16,2),2], yend = horiz_pca[seq(2,16,2),2]),
               color = 'grey85') +
  geom_segment(aes(x = intersection[1,1], xend = vert_pca[8,1],
                   y = intersection[1,2], yend = vert_pca[8,2]),
               color = 'black',size = 1) +
  geom_segment(aes(x = intersection[1,1], xend = horiz_pca[10,1],
                   y = intersection[1,2], yend = horiz_pca[10,2]),
               color = 'black', size = 1) +
  geom_segment(aes(x = -3.5, xend = 3.5, y = 0, yend = 0), color = 'darkorange1', size = 1.5,
               arrow = arrow(ends = 'both', length = unit(0.1, "inches"))) + 
  geom_segment(aes(x = 0, xend = 0, y = -1.8, yend = 1.8), color = 'royalblue1', size = 1.5,
               arrow = arrow(ends = 'both', length = unit(0.1, "inches"))) + 
  geom_point(data = data.frame(scores), aes(x = X1, y = X2)) + 
  coord_fixed(ratio = 1, ylim = c(-2.5,2.5)) + 
  theme(panel.border = element_blank(), panel.grid = element_blank(),
        axis.title = element_blank(), axis.text = element_blank(), axis.ticks = element_blank())
ggsave('D:/Research/_plots/pca101c.jpg', width = 5)

```

#### VARIABLE INTERPRETATION #### 

```{r}
## load data ####
load('./_sherlock/_results/regression_dataframe_1120.Rdata')
load('./_sherlock/_results/regression_results_1120.Rdata')
load('./_sherlock/_results/f.rf_1120.Rdata')
load('./_sherlock/_results/partialdependence_1120.Rdata')

mslasso.vars
dimension <- 
  data.frame(varnames = mslasso.vars,
             dimension = c('E', 'H', 'E', 'H', 'V', 'H', 'V', 'V', 
                           'H', 'H', 'H', 'H', 'E', 'H', 'V', 'V'),
             fullnames = c('Land Area', 'Storm Duration',
                           'Average Elevation', 'El Nino Index', 'Flood Experience', 'Storm Intensity',
                           'Median Income', 'Median Structure Year Built', 
                           'Max Storm Precipitation', 'Precipitation in \nPrevious Month', 
                           'Precipitation in \nPrevious Week', 'Month of Year', 'Number of \nSingle Family Homes', 
                           '% Soil Moisture', 'Housing & Transportation \nVulnerability', 
                           'Minority Status & \nLanguage Vulnerability'))

```

```{r}
## partial dependence plots #### 

## sort mslasso.vars in order of importance
importance <- f.rf$finalModel$importance %>%
  as.data.frame %>%
  rownames_to_column(var = 'varnames') %>%
  arrange(desc(MeanDecreaseAccuracy))
# mslasso.vars <- mslasso.vars[match(importance$varnames, mslasso.vars)]

## plot log likelihoods
for (i in 1:length(mslasso.vars)) {
  index <- which(lapply(partials, function(x) attr(x, 'varname'))  == mslasso.vars[i])
  line.color <- ggcolor(3)[as.numeric(dimension[dimension$varnames == mslasso.vars[i], 'dimension'])]
  g <- ggplot() +
    geom_smooth(data = data.frame(partials[[index]]), aes(x = x, y = y),
                method = 'loess', span = 0.25, level = 0.95,
                color = line.color, fill = 'grey80', size = 1) +
    geom_rug(data = data.frame(data = sample(df.mslasso[,mslasso.vars[i]], size = 1000)),
             aes(x = data)) +
    labs(x = mslasso.vars[i]) +
    scale_x_continuous(expand = c(0,0)) + scale_y_continuous(expand = c(0.1,0.1)) +
    theme_classic() +
    theme(plot.margin = ggplot2::margin(1, 10, 1, 10),
          axis.title.y = element_blank(),
          axis.line = element_line(color = 'grey50'),
          axis.ticks = element_line(color = 'grey50'))
  assign(paste0('g', i), g)
}
# jpeg('D:/Research/_plots/partialdependence.jpg', width = 6, height = 5, units = 'in', res = 144)
grid.arrange(g1, g2, g3, g4, g5, g6, g7, g8, g9, nrow = 3,
             top = textGrob(expression(bold('Partial Dependence Plots')),
                            vjust = 0.25, gp = gpar(cex = 1.1)))
grid.arrange(g10, g11, g12, g13, g14, g15, g16, nrow = 3,
             top = textGrob(expression(bold('Partial Dependence Plots')),
                            vjust = 0.25, gp = gpar(cex = 1.1)))

```

```{r}
## hazard plots ####
index <- which(lapply(partials, function(x) attr(x, 'varname'))  == 'rainyseason')
ggplot() + 
  geom_smooth(data = data.frame(partials[[index]]),
              aes(x = ymd('2018-10-01') + days(round(x)), y = y), formula = 'y ~ x',
              method = 'loess', span = 0.35, level = 0.9,
              color = 'black', fill = 'grey60', size = 1) +
  geom_rug(data = data.frame(data = sample(df.mslasso$rainyseason, size = 1000)), 
           aes(x = ymd('2018-10-01') + days(round(data)))) + 
  labs(x = 'Month of Year', y = 'Chance of Damaging Event') + 
  scale_x_date(expand = c(0,0), date_labels = '%b') + 
  coord_cartesian(xlim = c(ymd('2018-10-01'), ymd('2019-04-01'))) + 
  scale_y_continuous(expand = c(0.1,0.1)) + 
  theme_classic() + 
  theme(plot.margin = ggplot2::margin(1, 10, 1, 10),
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.line = element_line(color = 'grey50'), axis.ticks = element_line(color = 'grey50'))
ggsave('./_plots/pd_h1.jpg', width = 3, height = 3)

ymd('2018-10-01') + days(round(partials[[index]][,'x']))
?scale_x_date
```

```{r}
## exposure plots ####
# index <- which(lapply(partials, function(x) attr(x, 'varname'))  == 'developed')
# ggplot() + 
#   geom_smooth(data = data.frame(partials[[index]]),
#               aes(x = x, y = y), formula = 'y ~ x',
#               method = 'loess', span = 0.25, level = 0.95,
#               color = 'black', fill = 'grey60', size = 1) + 
#   geom_rug(data = data.frame(data = california$developed), aes(x = data)) + 
#   labs(x = '% Developed Land Cover', y = 'Chance of \nDamaging Event') + 
#   scale_x_continuous(expand = c(0,0), labels = scales::percent_format(accuracy = 1)) + 
#   scale_y_continuous(expand = c(0.1,0.1)) + 
#   theme_classic() + 
#   theme(plot.margin = ggplot2::margin(1, 10, 1, 10),
#         axis.text.y = element_blank(), axis.ticks.y = element_blank(),
#         # axis.title.y = element_blank(),
#         axis.line = element_line(color = 'grey50'), axis.ticks = element_line(color = 'grey50'))
# ggsave('./_plots/pd_e1.jpg', width = 3, height = 2)
# ggplot(california) + 
#   geom_sf(aes(fill = developed), color = 'grey40', size = 0.25) + 
#   scale_fill_distiller(name = '', palette = 'Reds', direction = 1) + 
#   theme_void()
# ggsave('./_plots/pd_e1_map.jpg', width = 4, height = 4)

index <- which(lapply(partials, function(x) attr(x, 'varname'))  == 'pct_floodplain')
ggplot() + 
  geom_smooth(data = data.frame(partials[[index]]),
              aes(x = x, y = y), formula = 'y ~ x',
              method = 'loess', span = 0.35, level = 0.95,
              color = 'black', fill = 'grey60', size = 1) + 
  geom_rug(data = data.frame(data = california$pct_floodplain), aes(x = data)) + 
  labs(x = '% Land Area in 100-Year Floodplain', y = 'Chance of Damaging Event') + 
  scale_x_continuous(expand = c(0,0), labels = scales::percent_format(accuracy = 1)) + 
  scale_y_continuous(expand = c(0.1,0.1)) + 
  theme_classic() + 
  theme(plot.margin = ggplot2::margin(1, 10, 1, 10),
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.line = element_line(color = 'grey50'), axis.ticks = element_line(color = 'grey50'))
ggsave('./_plots/pd_e2.jpg', width = 3, height = 3)
ggplot(california) +
  geom_sf(aes(fill = pct_floodplain), color = 'grey40', size = 0.25) +
  scale_fill_distiller(name = '', palette = 'Reds', direction = 1, 
                       labels = scales::percent_format(accuracy = 1)) +
  theme_void()
ggsave('./_plots/pd_e2_map.jpg', width = 4, height = 4)

```

```{r}
## vulnerability plots ####
index <- which(lapply(partials, function(x) attr(x, 'varname'))  == 'SVI_houstrans')
ggplot() + 
  geom_smooth(data = data.frame(partials[[index]]),
              aes(x = x, y = y), formula = 'y ~ x',
              method = 'loess', span = 0.25, level = 0.95,
              color = 'black', fill = 'grey60', size = 1) + 
  geom_rug(data = data.frame(data = california$SVI_houstrans), aes(x = data)) + 
  labs(x = 'SVI', y = 'Chance of Damaging Event') + 
  scale_x_continuous(expand = c(0,0)) + 
  scale_y_continuous(expand = c(0.1,0.1)) + 
  theme_classic() + 
  theme(plot.margin = ggplot2::margin(1, 10, 1, 10),
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.line = element_line(color = 'grey50'), axis.ticks = element_line(color = 'grey50'))
ggsave('./_plots/pd_v1.jpg', width = 3, height = 2)
ggplot(california) + 
  geom_sf(aes(fill = SVI_houstrans), color = 'grey40', size = 0.25) + 
  scale_fill_distiller(name = '', palette = 'Reds', direction = 1) + 
  theme_void()
ggsave('./_plots/pd_v1_map.jpg', width = 4, height = 4)

index <- which(lapply(partials, function(x) attr(x, 'varname'))  == 'med_income')
ggplot() + 
  geom_smooth(data = data.frame(partials[[index]]),
              aes(x = x, y = y), formula = 'y ~ x',
              method = 'loess', span = 0.35, level = 0.95,
              color = 'black', fill = 'grey60', size = 1) + 
  geom_rug(data = data.frame(data = california$med_income), aes(x = data)) + 
  labs(x = 'Median Income', y = 'Chance of Damaging Event') + 
  scale_x_continuous(expand = c(0,0), labels = scales::dollar_format(scale = 1e-3, suffix = 'K')) + 
  scale_y_continuous(expand = c(0.1,0.1)) + 
  theme_classic() + 
  theme(plot.margin = ggplot2::margin(1, 10, 1, 10),
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.line = element_line(color = 'grey50'), axis.ticks = element_line(color = 'grey50'))
ggsave('./_plots/pd_v2.jpg', width = 3, height = 3)
ggplot(california) + 
  geom_sf(aes(fill = med_income), color = 'grey40', size = 0.25) + 
  scale_fill_distiller(name = '', palette = 'Reds', direction = 1,
                       labels = scales::dollar_format(scale = 1e-3, suffix = 'K')) + 
  theme_void()
ggsave('./_plots/pd_v2_map.jpg', width = 4, height = 4)

index <- which(lapply(partials, function(x) attr(x, 'varname'))  == 'med_struct_age')
ggplot() + 
  geom_smooth(data = data.frame(partials[[index]]),
              aes(x = x, y = y), formula = 'y ~ x',
              method = 'loess', span = 0.25, level = 0.95,
              color = 'black', fill = 'grey60', size = 1) + 
  geom_rug(data = data.frame(data = jitter(california$med_struct_age)), aes(x = data)) + 
  labs(x = 'Median Structure Year Built', y = 'Chance of Damaging Event') + 
  scale_x_continuous(expand = c(0,0)) + 
  scale_y_continuous(expand = c(0.1,0.1)) + 
  coord_cartesian(xlim = c(1960, NA)) + 
  theme_classic() + 
  theme(plot.margin = ggplot2::margin(1, 10, 1, 10),
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.line = element_line(color = 'grey50'), axis.ticks = element_line(color = 'grey50'))
ggsave('./_plots/pd_v3.jpg', width = 3, height = 2)
ggplot(california) + 
  geom_sf(aes(fill = med_struct_age), color = 'grey40', size = 0.25) + 
  scale_fill_distiller(name = '', palette = 'Reds', direction = 1) + 
  theme_void()
ggsave('./_plots/pd_v3_map.jpg', width = 4, height = 4)

```

```{r}
## variable importance by H/E/V ####
importance.plot <- importance %>% 
  full_join(dimension, by = 'varnames') %>% 
  arrange(MeanDecreaseAccuracy) %>% 
  mutate(varnames = forcats::fct_inorder(varnames),
         fullnames = forcats::fct_inorder(fullnames),
         dimension = factor(dimension, levels = c('H', 'E', 'V'))) %>% 
  arrange(desc(MeanDecreaseAccuracy))

## plot global variable importance
ggplot(importance.plot[1:10,]) + 
  geom_col(aes(x = fullnames, y = MeanDecreaseAccuracy), width = 0.5,
           fill = rgb(140,21,21, maxColorValue = 255)) + 
  scale_y_continuous(name = 'Relative Importance', expand = c(0,0)) + 
  coord_flip() + 
  theme(panel.border = element_blank(), panel.grid.major.y = element_blank(), 
        axis.line.x = element_line(), 
        axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        axis.title.y = element_blank(), axis.text.y = element_text(size = 10))
ggsave('./_plots/variableimportance.jpg', width = 5, height = 4)


ggplot(importance.plot[1:10,]) + 
  geom_col(aes(x = fullnames, y = MeanDecreaseAccuracy, fill = factor(dimension)),
           width = 0.5, show.legend = FALSE) + 
  scale_fill_manual(labels = c('Hazard', 'Exposure', 'Vulnerability'), name = '',
                    values = c(rgb(242,168,168, maxColorValue = 255), 
                               rgb(164,24,24, maxColorValue = 255),
                               rgb(75,13,13, maxColorValue = 255))) +
  scale_y_continuous(name = 'Relative Importance', expand = c(0,0)) + 
  coord_flip() + 
  theme(panel.border = element_blank(), panel.grid.major.y = element_blank(), 
        axis.line.x = element_line(), 
        axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        axis.title.y = element_blank(), axis.text.y = element_text(size = 10))
ggsave('./_plots/variableimportance_HEV.jpg', width = 5, height = 4)

ggplot(importance.plot[1:10,]) + 
  geom_col(aes(x = fullnames, y = MeanDecreaseAccuracy, fill = factor(dimension))) + 
  scale_fill_manual(labels = c('Hazard', 'Exposure', 'Vulnerability'), name = '',
                    values = c(rgb(242,168,168, maxColorValue = 255), 
                               rgb(164,24,24, maxColorValue = 255),
                               rgb(75,13,13, maxColorValue = 255)))
ggsave('./_plots/variableimportance_HEV_legend.jpg', width = 5, height = 4)


```

```{r}
## HEV donut chart ####
importance.plot %>% 
  group_by(dimension) %>% 
  summarize(decrease_accuracy = sum(MeanDecreaseAccuracy), .groups = 'drop')
H <- 0.4405878		
E <- 0.3461808	
V <- 0.1985992		

ggplot() + 
  geom_rect(aes(xmin = 3, xmax = 4, ymin = 0, ymax = H, fill = 'Hazard')) +
  geom_rect(aes(xmin = 3, xmax = 4, ymin = H, ymax = H+V, fill = 'Vulnerability')) +
  geom_rect(aes(xmin = 3, xmax = 4, ymin = H+V, ymax = H+V+E, fill = 'Exposure')) +
  scale_fill_manual(values = c(rgb(214,32,32, maxColorValue = 255),
                               rgb(240,154,154, maxColorValue = 255), 
                               rgb(75,13,13, maxColorValue = 255))) +
  geom_text(aes(x = 3.5, y = c(H/2, H + V/2, H + V + E/2), 
                label = paste0(round(c(H,V,E)*100, 1), '%')),
            color = 'white', size = 6, fontface = 'bold') + 
  coord_polar("y", start = pi) + 
  xlim(c(2,4)) + theme_void()
ggsave('./_plots/HEVdonut.jpg', width = 5, height = 5)

```

```{r}
## aggregation by region ####
temp <- f.rf$finalModel$localImportance %>% t %>% data.frame %>% 
  cbind(county = obs.id$county) %>% 
  group_by(county) %>% 
  summarize_all(mean, .groups = 'drop') %>% 
  right_join(tigris::counties(state = 'CA', class = 'sf'), ., by = c('NAME' = 'county'))

map.color <- 'Blues'
ggplot() + 
  geom_sf(data = temp, aes(fill = precip.max), size = 0.5, show.legend = FALSE) + 
  ggtitle('Relative Importance of \nMax Precipitation') + 
  scale_fill_distiller(palette = map.color, direction = 1) + 
  theme_void()
# ggsave('./_plots/regionmap1.jpg', width = 4, height = 4)
ggplot() + 
  geom_sf(data = temp, aes(fill = days.max), size = 0.5, show.legend = FALSE) + 
  ggtitle('Relative Importance of \nStorm Duration') + 
  scale_fill_distiller(palette = map.color, direction = 1) + 
  theme_void()
# ggsave('./_plots/regionmap2.jpg', width = 4, height = 4)
ggplot() + 
  geom_sf(data = temp, aes(fill = precip.prevweek), size = 0.5, show.legend = FALSE) + 
  ggtitle('Relative Importance of \nAntecedent Hydrology') + 
  scale_fill_distiller(palette = map.color, direction = 1) + 
  theme_void()
# ggsave('./_plots/regionmap3.jpg', width = 4, height = 4)
ggplot() + 
  geom_sf(data = temp, aes(fill = ENSO), size = 0.5, show.legend = FALSE) + 
  ggtitle('Relative Importance of \nEl Nino Conditions') + 
  scale_fill_distiller(palette = map.color, direction = 1) + 
  theme_void()
# ggsave('./_plots/regionmap4.jpg', width = 4, height = 4)
ggplot() + 
  geom_sf(data = temp, aes(fill = IVT_max), size = 0.5, show.legend = FALSE) + 
  ggtitle('Relative Importance of \nMax IVT') + 
  scale_fill_distiller(palette = map.color, direction = 1) + 
  theme_void()
ggplot() + 
  geom_sf(data = temp, aes(fill = precip.prevmonth), size = 0.5, show.legend = FALSE) + 
  ggtitle('Relative Importance of \nLast Month\'s Precip') + 
  scale_fill_distiller(palette = map.color, direction = 1) + 
  theme_void()
ggplot() + 
  geom_sf(data = temp, aes(fill = rainyseason.month), size = 0.5, show.legend = FALSE) + 
  ggtitle('Relative Importance of \nRainy Season') + 
  scale_fill_distiller(palette = map.color, direction = 1) + 
  theme_void()
ggplot() + 
  geom_sf(data = temp, aes(fill = soilmoisture), size = 0.5, show.legend = FALSE) + 
  ggtitle('Relative Importance of \nSoil Moisture') + 
  scale_fill_distiller(palette = map.color, direction = 1) + 
  theme_void()
```


